on:
  push:
    branches: [actions-branch]
jobs:
    # Generate a markdown file from godoc.
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.16.4'
        - name: Setup goreadme
          run: go get github.com/posener/goreadme/cmd/goreadme@v1.4.0
        - name: Run goreadme
          run: |
            for PKG in ./pkg/*
            do
              (cd $PKG && goreadme -functions -types -recursive > ./README.md)
            done
          env:
            # Run the tool in non-CI mode: we will take care of git add and push ourselves.
            CI: false
        - name: Commit the generated README files.
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add ./pkg/**/*.md
            git commit -m "run goreadme"
            git push
