on: pull_request
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.16.4'
        - name: Run tests
          run: go test ./...
